import 'dotenv/config'

const PORT = process.env.PORT 
const DATABASE_CONNECTION_URL=process.env.DATABASE_URL
const REDIS_PORT = process.env.REDIS_PORT 
const REDIS_HOST=process.env.REDIS_HOST
const REDIS_PASSWORD = process.env.REDIS_PASSWORD 
const REDIS_CACHE_EXPIRY=process.env.REDIS_CACHE_EXPIRY
const RAZORPAY_API_BASE_URL=process.env.RAZORPAY_API_BASE_URL
const RAZORPAY_API_SECRET=process.env.RAZORPAY_API_SECRET
const RAZORPAY_API_ID=process.env.RAZORPAY_API_ID as string
const RAZORPAY_WEBHOOK_SECRET=process.env.RAZORPAY_WEBHOOK_SECRET


export {
    PORT,
    DATABASE_CONNECTION_URL,
    REDIS_CACHE_EXPIRY,
    REDIS_HOST,
    REDIS_PASSWORD,
    REDIS_PORT,
    RAZORPAY_API_ID,
    RAZORPAY_API_BASE_URL,
    RAZORPAY_API_SECRET,
    RAZORPAY_WEBHOOK_SECRET
}